### ISSUE TITLE
[PATHWAY TO SUCCESS] Create Pathway To Success HomePage

### ISSUE THREAD

**Issue by boltdynamics** [xplorer-io/website#69]
Figma - https://www.figma.com/design/fQssgttgmTJNUu8mIzlxcO/Xplorers?node-id=0-1&node-type=canvas&t=lWALLdbK3N8n9ERh-0

![Image](https://github.com/user-attachments/assets/adbc1989-4e35-4700-a2a0-ec5ba10edee1)

**Comment by DipeshGainju** [comment]
@yashcrest @pratibhapaudel @Aaasisss working on it.
