### ISSUE TITLE
[All Page] Fix margins for mobile view for various UI elements in home page

### ISSUE THREAD

**Issue by yashcrest** [xplorer-io/website#83]
- Need to fix margins on heading section for mobile view.
- Fix right & left margin for home section card view. 

https://github.com/user-attachments/assets/e3edf665-a656-47f7-abb0-e6075b4a1f92

**Comment by raikiran07** [comment]
Hi, Yash I would like to work on this issue if you could please assign it to me.

**Comment by yashcrest** [comment]
@raikiran07  this issue has been solved in PR #85 

Will let you know if there new Issues that you could work on 😃
