### ISSUE TITLE
Investigate ways to cache images - images look blurry in the website

### ISSUE THREAD

**Issue by boltdynamics** [xplorer-io/website#87]

**Comment by yashcrest** [comment]
resources : 
https://web.dev/articles/image-cdns
https://gist.github.com/NawalJAhmed/2168f7659c08b6a033e7f6daf8db69a6

**Comment by yashcrest** [comment]
# Diff in self-managed image CDNs & Third-party Image CDNs
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/4d19ef90-eac1-4f8a-86b1-fb888fbddcfe">

**Comment by yashcrest** [comment]
we will be moving forward with Cloudinary as Images CDN hosting.
